### ISSUE TITLE
EE3 email_send hook php error

### ISSUE THREAD

**Issue by obfuscode** [cld-agency/ee-html-email#2]
The pass by reference `$data` variable in the `email_send(&$data)` method throws this PHP warning:
>Parameter 1 to Cld_html_email_ext::email_send() expected to be a reference, value given

**Comment by simcen** [comment]
Will be fixed with https://github.com/cld-agency/ee-html-email/pull/3

**Comment by thisisjamessmith** [comment]
Thanks for reporting. Should be fixed now in version 1.0.1.
